import { Download, ReceiptText } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

export type ReceiptItem = {
  name: string;
  strength?: string | null;
  dosage?: string | null;
  duration?: string | null;
  quantity?: string | null;
};

export type ReceiptOrder = {
  id: string;
  created_at: string;
  paid_at?: string | null;
  patient_name?: string | null;
  doctor_name?: string | null;
  quoted_amount?: number | string | null;
  currency?: string | null;
  razorpay_order_id?: string | null;
  razorpay_payment_id?: string | null;
  prescription_items: ReceiptItem[];
};

export type ReceiptPharmacy = {
  name?: string | null;
  address?: string | null;
  phone?: string | null;
} | null;

const money = (order: ReceiptOrder) => {
  const symbol = (order.currency ?? "INR") === "INR" ? "₹" : `${order.currency ?? ""} `;
  return `${symbol}${Number(order.quoted_amount ?? 0).toFixed(2)}`;
};

const when = (v?: string | null) => (v ? new Date(v).toLocaleString() : "—");

const detail = (m: ReceiptItem) =>
  [m.strength, m.dosage, m.duration, m.quantity ? `Qty ${m.quantity}` : null]
    .filter(Boolean)
    .join(" · ");

const escapeHtml = (v: string) =>
  v.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string,
  );

/** Opens a print-ready receipt so the user can save it as a PDF. */
export function downloadReceipt(order: ReceiptOrder, pharmacy: ReceiptPharmacy) {
  const rows = order.prescription_items
    .map(
      (m) =>
        `<tr><td><strong>${escapeHtml(m.name)}</strong>${
          detail(m) ? `<div class="muted">${escapeHtml(detail(m))}</div>` : ""
        }</td></tr>`,
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8" />
<title>Receipt ${escapeHtml(order.id.slice(0, 8))} — MedicPassport</title>
<style>
  body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#0A1626;margin:0;padding:32px;}
  .wrap{max-width:620px;margin:0 auto;}
  h1{font-size:20px;margin:0 0 2px;color:#0B2545;}
  .muted{color:#5b6b7f;font-size:12px;}
  .badge{display:inline-block;background:#EAF3FC;color:#1D7DD6;border-radius:999px;padding:4px 12px;font-size:12px;font-weight:600;margin-top:12px;}
  table{width:100%;border-collapse:collapse;margin-top:8px;}
  td{padding:10px 0;border-bottom:1px solid #e5ebf2;font-size:14px;vertical-align:top;}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 16px;margin-top:16px;font-size:13px;}
  .total{display:flex;justify-content:space-between;align-items:center;margin-top:20px;padding-top:14px;border-top:2px solid #0B2545;font-size:18px;font-weight:700;}
  h2{font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:#5b6b7f;margin:26px 0 0;}
</style></head><body><div class="wrap">
  <h1>${escapeHtml(pharmacy?.name ?? "Pharmacy")}</h1>
  <div class="muted">${escapeHtml(pharmacy?.address ?? "")}${
    pharmacy?.phone ? ` · ${escapeHtml(pharmacy.phone)}` : ""
  }</div>
  <div class="badge">Payment received</div>
  <div class="grid">
    <div><div class="muted">Receipt no.</div>${escapeHtml(order.id.slice(0, 8).toUpperCase())}</div>
    <div><div class="muted">Paid on</div>${escapeHtml(when(order.paid_at))}</div>
    <div><div class="muted">Patient</div>${escapeHtml(order.patient_name || "—")}</div>
    <div><div class="muted">Doctor</div>${escapeHtml(order.doctor_name || "—")}</div>
    <div><div class="muted">Payment ID</div>${escapeHtml(order.razorpay_payment_id ?? "—")}</div>
    <div><div class="muted">Order ID</div>${escapeHtml(order.razorpay_order_id ?? "—")}</div>
  </div>
  <h2>Order summary</h2>
  <table>${rows}</table>
  <div class="total"><span>Total paid</span><span>${escapeHtml(money(order))}</span></div>
  <p class="muted" style="margin-top:24px">Paid securely via Razorpay · Generated by MedicPassport on ${escapeHtml(
    new Date().toLocaleString(),
  )}</p>
</div><script>window.onload=function(){window.print()}</script></body></html>`;

  const win = window.open("", "_blank", "width=720,height=900");
  if (!win) {
    const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `receipt-${order.id.slice(0, 8)}.html`;
    a.click();
    URL.revokeObjectURL(url);
    return;
  }
  win.document.write(html);
  win.document.close();
}

export function PaymentReceiptDialog({
  order,
  pharmacy,
  open,
  onOpenChange,
}: {
  order: ReceiptOrder | null;
  pharmacy: ReceiptPharmacy;
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  return (
    <Dialog open={open && Boolean(order)} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[92vw] rounded-2xl sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-base">
            <ReceiptText className="size-4 shrink-0 text-success" />
            Payment receipt
          </DialogTitle>
          <DialogDescription className="text-xs">
            {pharmacy?.name ?? "Pharmacy"} · Receipt {order?.id.slice(0, 8).toUpperCase()}
          </DialogDescription>
        </DialogHeader>

        {order ? (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3 rounded-xl bg-secondary/70 p-3 text-xs">
              <div>
                <p className="text-muted-foreground">Paid on</p>
                <p className="font-medium">{when(order.paid_at)}</p>
              </div>
              <div>
                <p className="text-muted-foreground">Patient</p>
                <p className="truncate font-medium">{order.patient_name || "—"}</p>
              </div>
              <div className="col-span-2 min-w-0">
                <p className="text-muted-foreground">Payment ID</p>
                <p className="truncate font-mono text-[11px]">{order.razorpay_payment_id ?? "—"}</p>
              </div>
            </div>

            <div>
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Order summary
              </p>
              <ul className="mt-2 max-h-52 space-y-2 overflow-y-auto">
                {order.prescription_items.map((m, i) => (
                  <li key={i} className="rounded-lg border border-border p-2.5">
                    <p className="truncate text-sm font-medium">{m.name}</p>
                    {detail(m) ? (
                      <p className="mt-0.5 truncate text-xs text-muted-foreground">{detail(m)}</p>
                    ) : null}
                  </li>
                ))}
              </ul>
            </div>

            <div className="flex items-center justify-between border-t border-border pt-3">
              <span className="text-sm text-muted-foreground">Total paid</span>
              <span className="text-lg font-semibold">{money(order)}</span>
            </div>

            <Button
              className="h-12 w-full rounded-xl text-base"
              onClick={() => downloadReceipt(order, pharmacy)}
            >
              <Download className="size-4" />
              Download receipt
            </Button>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}
